modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License 3.0"
issueTrackerURL="https://github.com/12345-mcpython/Obfuscate/issues"

[[mods]]
modId="obfuscate"
version="0.7.1"
displayName="Obfuscate"
updateJSONURL="https://programming-file.obs.cn-north-4.myhuaweicloud.com/obfuscate_update.json"
displayURL="https://github.com/12345-mcpython/Obfuscate/"
logoFile="obfuscate_logo.png"
credits="Cheers to these people for donating during the development: Fabbe50, Infinite Worlds, ALBERT, Mastef Chief, OstenTV, Robert Finley, PlayDashGaming, Shadow Bill-cat"
authors="MrCrayfish"
description="A simple library that adds in useful events"

[[dependencies.obfuscate]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.obfuscate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"

[modproperties.obfuscate]
    catalogueImageIcon="obfuscate_icon.png"
    configuredBackground="minecraft:textures/block/yellow_concrete.png"