modLoader="javafml"
loaderVersion="[32,)"
license="GNU General Public License 3.0"

[[mods]]
modId="obfuscate"
version="0.6.0"
displayName="Obfuscate"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/Obfuscate/master/update.json"
displayURL="https://mrcrayfish.com/"
logoFile="obfuscate.png"
credits="Cheers to these people for donating during the development: Fabbe50, Infinite Worlds, ALBERT, Mastef Chief, OstenTV, Robert Finley, PlayDashGaming, Shadow Bill-cat"
authors="MrCrayfish"
description="A simple library that adds in useful events"
itemIcon="minecraft:command_block"
configBackground="minecraft:textures/block/yellow_concrete.png"

[[dependencies.obfuscate]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.obfuscate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"